using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace PopularGroupsApp.Models
{
    public class Band
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Style { get; set; }
        public string Cities { get; set; }

        public string Description { get; set; } 

        public string ImagePath { get; set; }

        

        public ICollection<Concert> concerts { get; set; } = new List<Concert>();

 

        public static List<Band> bandsCreate() 
        {


                    List<Band> bands = new List<Band>()
        {
            new Band { Id = 1, Name = "Crimson Echo", Style = "Progressive Rock", Cities = "Madrid", ImagePath = "~/Images/01CrimsonEcho.PNG", Description = "Crimson Echo es una banda de Progressive Rock que nació en el corazón de Madrid, fusionando sonidos clásicos del rock con atmósferas experimentales y complejas estructuras musicales. Su estilo se caracteriza por riffs potentes, cambios de ritmo inesperados y letras cargadas de simbolismo, que invitan a reflexionar sobre la vida y la sociedad. Con influencias de bandas legendarias como Pink Floyd y King Crimson, han logrado crear un sonido propio que mezcla lo vintage con lo contemporáneo. Sus conciertos son una experiencia inmersiva, donde la música se acompaña de visuales psicodélicos y una puesta en escena que atrapa al público desde el primer acorde." },

            new Band { Id = 2, Name = "Velvet Storm", Style = "Hard Rock", Cities = "Barcelona", ImagePath = "~/Images/02VelvetStorm.PNG", Description = "Velvet Storm es una banda de Hard Rock originaria de Barcelona, conocida por su energía arrolladora y su sonido potente que mezcla riffs clásicos con una actitud moderna. Sus canciones están cargadas de fuerza, con guitarras distorsionadas, baterías contundentes y letras que evocan rebeldía y pasión. En cada concierto, Velvet Storm ofrece un espectáculo electrizante, donde la intensidad del rock se combina con una puesta en escena vibrante y cercana al público. Influenciados por leyendas del género, han logrado crear un estilo propio que los posiciona como una de las propuestas más prometedoras del panorama nacional." },

            new Band { Id = 3, Name = "Neon Mirage", Style = "Synthwave", Cities = "Valencia", ImagePath = "~/Images/03NeonMirage.PNG", Description = "Neon Mirage es una banda de Synthwave originaria de Valencia, que transporta a su público a un universo retro-futurista lleno de luces de neón y sonidos electrónicos envolventes. Su música combina ritmos pulsantes, sintetizadores nostálgicos y melodías hipnóticas que evocan la estética de los años 80 con un toque contemporáneo. Cada actuación es una experiencia visual y sonora, donde los colores vibrantes y las proyecciones digitales se funden con beats electrónicos para crear una atmósfera única. Con influencias del cine retro y la cultura cyberpunk, Neon Mirage se ha convertido en un referente para quienes buscan una inmersión total en el mundo del Synthwave."},

            new Band { Id = 4, Name = "Iron Howl", Style = "Heavy Metal", Cities = "Sevilla", ImagePath = "~/Images/04IronHowl.PNG", Description = "Iron Howl es una banda de Heavy Metal originaria de Sevilla, reconocida por su sonido crudo y poderoso que hace vibrar cada escenario. Sus composiciones están cargadas de riffs agresivos, solos vertiginosos y una voz desgarradora que transmite fuerza y rebeldía. Inspirados por las leyendas del metal clásico, Iron Howl aporta un toque contemporáneo que los distingue en la escena nacional. Sus conciertos son auténticas explosiones de energía, donde la intensidad del metal se combina con una puesta en escena oscura y envolvente, creando una experiencia que ningún amante del género quiere perderse."},

            new Band { Id = 5, Name = "Blue Horizon", Style = "Blues", Cities = "Bilbao", ImagePath = "~/Images/05BlueHorizon.PNG", Description ="Blue Horizon es una banda de Blues originaria de Bilbao, que destaca por su sonido cálido y auténtico, inspirado en las raíces del género. Sus composiciones combinan guitarras melódicas, ritmos pausados y letras cargadas de sentimiento, creando una atmósfera íntima que conecta con el alma del público. Con influencias del blues clásico y toques contemporáneos, Blue Horizon ofrece conciertos donde la emoción y la técnica se funden en cada acorde. Su propuesta es un viaje sonoro que evoca paisajes urbanos y emociones profundas, ideal para quienes buscan música con carácter y honestidad."},

            new Band { Id = 6, Name = "Solar Drift", Style = "Indie Pop", Cities = "Zaragoza", ImagePath = "~/Images/06SolarDrift.PNG", Description ="Solar Drift es una banda de Indie Pop originaria de Zaragoza, que destaca por su sonido fresco y luminoso, lleno de melodías pegadizas y atmósferas envolventes. Sus canciones combinan guitarras suaves, sintetizadores brillantes y letras que transmiten optimismo y emociones cotidianas. Con influencias del pop alternativo y la música indie internacional, Solar Drift crea un estilo único que conecta con quienes buscan autenticidad y energía positiva. Sus conciertos son una experiencia vibrante, donde la cercanía con el público y la estética colorida se convierten en protagonistas."},

            new Band { Id = 7, Name = "Echoes of Dawn", Style = "Alternative Rock", Cities = "Málaga", ImagePath = "~/Images/07EchoesofDawn.PNG", Description ="Echoes of Dawn es una banda de Alternative Rock originaria de Málaga, que se caracteriza por su sonido intenso y emocional, donde las guitarras atmosféricas se mezclan con ritmos dinámicos y letras cargadas de significado. Su propuesta combina la fuerza del rock alternativo con influencias indie y toques experimentales, creando canciones que conectan con el público a través de historias profundas y melodías envolventes. Cada concierto es una experiencia vibrante, con una puesta en escena cuidada y una energía que atrapa desde el primer acorde, consolidando a Echoes of Dawn como una de las bandas más prometedoras del panorama nacional."},

            new Band { Id = 8, Name = "Shadow Carnival", Style = "Gothic Rock", Cities = "Granada", ImagePath = "~/Images/08ShadowCarnival.PNG", Description ="Shadow Carnival es una banda de Gothic Rock originaria de Granada, que envuelve a su público en una atmósfera oscura y teatral. Su música combina guitarras profundas, bajos densos y voces cargadas de dramatismo, creando un sonido que evoca misterio y emociones intensas. Con influencias del rock gótico clásico y elementos visuales inspirados en el arte barroco y la estética victoriana, Shadow Carnival convierte cada concierto en un espectáculo único, donde la música se fusiona con luces tenues y escenografía sombría. Su propuesta es ideal para quienes buscan una experiencia artística que trascienda lo convencional."},

            new Band { Id = 9, Name = "Pixel Riot", Style = "Electronic Punk", Cities = "Santander", ImagePath = "~/Images/09PixelRiot.PNG", Description ="Pixel Riot es una banda de Electronic Punk originaria de Santander, que rompe esquemas con su sonido explosivo y su estética digital. Su música combina la agresividad del punk con ritmos electrónicos frenéticos, creando un estilo único que mezcla rebeldía y tecnología. Con sintetizadores distorsionados, beats acelerados y letras cargadas de actitud, Pixel Riot convierte cada concierto en una experiencia caótica y electrizante. Sus shows son un despliegue visual lleno de luces de neón, gráficos pixelados y energía sin límites, ideales para quienes buscan una propuesta audaz y futurista dentro del panorama musical."},

            new Band { Id = 10, Name = "Golden Roots", Style = "Country", Cities = "Salamanca", ImagePath = "~/Images/10GoldenRoots.PNG", Description ="Golden Roots es una banda de Country originaria de Salamanca, que transmite la esencia más pura del género con un toque contemporáneo. Sus canciones evocan paisajes abiertos, historias de vida y emociones sinceras, acompañadas por guitarras acústicas, banjos y armonías cálidas. Con influencias del country clásico y sonidos modernos, Golden Roots crea una experiencia musical que conecta con la tradición sin perder frescura. Sus conciertos son íntimos y cercanos, donde la autenticidad y la pasión por la música se convierten en protagonistas."},

            new Band { Id = 11, Name = "Lunar Tide", Style = "Ambient", Cities = "Cádiz", ImagePath = "~/Images/11LunarTide.PNG" , Description ="Lunar Tide es una banda de Ambient originaria de Cádiz, que se distingue por crear paisajes sonoros etéreos y envolventes. Su música combina texturas suaves, sonidos naturales y sintetizadores delicados para transportar al oyente a un estado de calma y contemplación. Inspirados en la conexión entre el mar y la luna, sus composiciones evocan sensaciones de fluidez y serenidad, ideales para quienes buscan una experiencia musical introspectiva. Cada concierto es una inmersión sensorial, donde la luz tenue y los sonidos ambientales se funden para ofrecer un viaje único hacia la tranquilidad"},

            new Band { Id = 12, Name = "Crater Kings", Style = "Grunge", Cities = "Toledo", ImagePath = "~/Images/12CraterKings.PNG", Description ="Crater Kings es una banda de Grunge originaria de Toledo, que revive la esencia cruda y rebelde del movimiento noventero con un toque contemporáneo. Su sonido se caracteriza por guitarras distorsionadas, bajos potentes y letras cargadas de emociones intensas, que exploran la frustración, la libertad y la búsqueda de identidad. Con influencias de bandas icónicas como Nirvana y Pearl Jam, Crater Kings ofrece conciertos llenos de energía y autenticidad, donde la conexión con el público se convierte en el núcleo de la experiencia. Su propuesta es ideal para quienes buscan un rock visceral y sin artificios."},

            new Band { Id = 13, Name = "Ruby Vortex", Style = "Pop Rock", Cities = "Alicante", ImagePath = "~/Images/13RubyVortex.PNG", Description ="Ruby Vortex es una banda de Pop Rock originaria de Alicante, que destaca por su sonido vibrante y lleno de energía. Sus canciones combinan melodías pegadizas con guitarras potentes y ritmos dinámicos, creando un estilo que conecta tanto con los amantes del pop como con los seguidores del rock clásico. Con letras que hablan de emociones intensas y experiencias cotidianas, Ruby Vortex ofrece conciertos cargados de frescura y cercanía, donde la interacción con el público y la fuerza de su música se convierten en protagonistas. Su propuesta es ideal para quienes buscan una mezcla perfecta entre intensidad y armonía."},

            new Band { Id = 14, Name = "Silent Ember", Style = "Acoustic Folk", Cities = "San Sebastián", ImagePath = "~/Images/14SilentEmber.PNG", Description ="Silent Ember es una banda de Acoustic Folk originaria de San Sebastián, que cautiva con su sonido íntimo y lleno de emociones. Sus canciones combinan guitarras acústicas, armonías suaves y letras poéticas que evocan paisajes naturales y sentimientos profundos. Con influencias del folk tradicional y toques contemporáneos, Silent Ember crea una atmósfera cálida y cercana en cada actuación, donde la sencillez y la autenticidad son protagonistas. Sus conciertos son experiencias únicas, ideales para quienes buscan música que conecte con la esencia y la calma."},

            new Band { Id = 15, Name = "Frostbite Anthem", Style = "Black Metal", Cities = "Valladolid", ImagePath = "~/Images/15FrostbiteAnthem.PNG", Description ="Frostbite Anthem es una banda de Black Metal originaria de Valladolid, que destaca por su sonido brutal y atmosférico, cargado de oscuridad y fuerza. Sus composiciones combinan riffs veloces, baterías demoledoras y voces desgarradoras, creando una experiencia sonora intensa y visceral. Inspirados en la crudeza del metal extremo y en paisajes gélidos, Frostbite Anthem ofrece conciertos que son auténticos rituales sonoros, donde la energía salvaje y la estética sombría se funden para transportar al público a un mundo de caos y poder. Su propuesta es ideal para quienes buscan la esencia más pura y agresiva del Black Metal."},

            new Band { Id = 16, Name = "Velocirhythm", Style = "Funk", Cities = "Pamplona", ImagePath = "~/Images/16Velocirhythm.PNG", Description ="Velocirhythm es una banda de Funk originaria de Pamplona, que destaca por su groove contagioso y su energía arrolladora en el escenario. Sus composiciones combinan líneas de bajo potentes, riffs rítmicos y secciones de viento que evocan la esencia del funk clásico con un toque moderno. Con influencias del soul y del jazz, Velocirhythm crea un sonido vibrante que invita a moverse y disfrutar. Cada concierto es una fiesta llena de ritmo, improvisación y conexión con el público, consolidando a la banda como una de las propuestas más frescas y dinámicas del panorama nacional."},

            new Band { Id = 17, Name = "Prism Parade", Style = "Disco", Cities = "Murcia", ImagePath = "~/Images/17PrismParade.PNG", Description ="Prism Parade es una banda de Disco originaria de Murcia, que trae de vuelta la esencia brillante y festiva de los años 70 con un toque moderno. Sus canciones están llenas de ritmos bailables, bajos funk y melodías pegadizas que invitan a moverse sin parar. Con influencias del soul y la música electrónica, Prism Parade crea una experiencia sonora y visual única, donde las luces, los colores y la energía se combinan para convertir cada concierto en una auténtica celebración. Su propuesta es ideal para quienes buscan diversión, glamour y el espíritu vibrante de la música disco."},

            new Band { Id = 18, Name = "Thunder Lotus", Style = "Stoner Rock", Cities = "Gijón", ImagePath = "~/Images/18ThunderLotus.PNG", Description ="Thunder Lotus es una banda de Stoner Rock originaria de Gijón, que se caracteriza por sus riffs pesados, ritmos hipnóticos y una atmósfera cargada de energía. Su sonido combina la crudeza del rock clásico con influencias psicodélicas, creando composiciones densas y envolventes que transportan al oyente a paisajes sonoros llenos de fuerza y misterio. Con letras introspectivas y una puesta en escena potente, Thunder Lotus convierte cada concierto en una experiencia vibrante, donde la distorsión y la intensidad son protagonistas. Ideal para quienes buscan un rock profundo y contundente."},

            new Band { Id = 19, Name = "Obsidian Pulse", Style = "Industrial", Cities = "Burgos", ImagePath = "~/Images/19ObsidianPulse.PNG", Description ="Obsidian Pulse es una banda industrial originaria de Burgos, conocida por su sonido oscuro y contundente que fusiona ritmos mecánicos con atmósferas densas y sintetizadores agresivos. Su propuesta artística se inspira en la estética post-apocalíptica y la crudeza del metal urbano, creando una experiencia sonora que evoca fábricas en ruinas y ciudades sumidas en sombras. Con letras introspectivas y críticas sociales, la banda busca transmitir la tensión entre la tecnología y la humanidad, ofreciendo un espectáculo cargado de energía, luces estroboscópicas y visuales industriales que sumergen al público en un universo distópico."},

            new Band { Id = 20, Name = "Aurora Veil", Style = "Dream Pop", Cities = "Córdoba", ImagePath = "~/Images/20AuroraVeil.PNG", Description ="Aurora Veil es una banda de Dream Pop originaria de Córdoba, que envuelve al oyente en paisajes sonoros etéreos y melódicos. Su música se caracteriza por voces suaves y reverberantes, guitarras con efectos envolventes y sintetizadores que evocan la sensación de un amanecer infinito. Con influencias del shoegaze y el pop alternativo, Aurora Veil crea atmósferas cargadas de nostalgia y luz, invitando a perderse en un universo donde la calma y la emoción se entrelazan. Sus letras exploran temas como la introspección, los sueños y la conexión con lo intangible, ofreciendo una experiencia sensorial única en cada presentación."},

            new Band { Id = 21, Name = "Scarlet Circuit", Style = "Electro Rock", Cities = "Tarragona", ImagePath = "~/Images/21ScarletCircuit.PNG", Description ="Scarlet Circuit es una banda de Electro Rock originaria de Tarragona, que combina la fuerza del rock con la energía vibrante de la electrónica. Su sonido se caracteriza por riffs potentes, sintetizadores dinámicos y ritmos que invitan a moverse, creando una experiencia sonora intensa y futurista. Con influencias del rock alternativo y la música electrónica contemporánea, Scarlet Circuit ofrece un espectáculo cargado de luces, beats y actitud, donde cada canción es una descarga eléctrica que conecta con la adrenalina del público. Sus letras exploran la dualidad entre lo humano y lo digital, reflejando la esencia de una era hiperconectada."},

            new Band { Id = 22, Name = "Midnight Howlers", Style = "Punk Rock", Cities = "Oviedo", ImagePath = "~/Images/22MidnightHowlers.PNG", Description ="Midnight Howlers es una banda de Punk Rock originaria de Oviedo, que desata pura energía con riffs crudos, baterías frenéticas y letras cargadas de actitud. Su sonido bebe de la esencia del punk clásico, pero con un toque moderno que mantiene la rebeldía intacta. Con influencias del hardcore y el garage rock, Midnight Howlers convierte cada concierto en una explosión de adrenalina, donde la conexión con el público es tan intensa como sus guitarras distorsionadas. Sus canciones hablan de libertad, inconformismo y noches sin reglas, reflejando el espíritu indomable que define a la banda."},

            new Band { Id = 23, Name = "Crystal Bones", Style = "Alternative Metal", Cities = "León", ImagePath = "~/Images/23CrystalBones.PNG", Description ="Crystal Bones es una banda de Alternative Metal originaria de León, que combina la potencia del metal con la experimentación sonora propia del rock alternativo. Su música se caracteriza por riffs pesados y atmosféricos, voces que oscilan entre la fuerza y la melancolía, y una base rítmica que aporta intensidad sin perder complejidad. Con influencias del metal progresivo y el grunge, Crystal Bones crea composiciones que exploran emociones profundas y contrastes, ofreciendo un espectáculo cargado de energía, luces dramáticas y una estética oscura pero elegante. Sus letras abordan temas existenciales, resiliencia y la búsqueda de identidad en un mundo cambiante."},

            new Band { Id = 24, Name = "Echo Nomads", Style = "World Music", Cities = "Castellón", ImagePath = "~/Images/24EchoNomads.PNG", Description ="Echo Nomads es una banda de World Music originaria de Castellón, que fusiona sonidos tradicionales de distintas culturas con ritmos contemporáneos para crear una experiencia musical única y global. Su propuesta se caracteriza por instrumentos étnicos, percusiones orgánicas y melodías que evocan viajes por paisajes sonoros diversos, desde lo mediterráneo hasta lo oriental. Con influencias del folk, la música tribal y el pop alternativo, Echo Nomads transmite un mensaje de unión y diversidad, invitando al público a conectar con raíces ancestrales mientras explora nuevas fronteras sonoras. Cada concierto es un viaje sensorial lleno de color, energía y emociones compartidas."},

        };


            //Propiedad de navegacion

            int count_bands = bands.Count;

            for (int i = 0; i < count_bands; i++) 
            {
                bands[i].concerts = Concert.concertCreate().Where(w => w.Id == bands[i].Id).ToList();
            }

            return bands;
        }
        
        
    }
}